import { ArrowUpRight, Cpu, Flame, Hexagon, Leaf } from 'lucide-react';
import { Link } from 'react-router-dom';
import { money, number, useDemo } from '../lib/demo';

export const Brand = () => <Link to="/zone" className="brand" data-testid="inc-hood-brand-logo"><span className="brand-symbol"><Hexagon strokeWidth={1.8}/><i /></span><span>inc<span className="brand-dot">.</span>hood</span></Link>;
export const ChainBadge = ({ testId = 'robinhood-chain-badge' }) => <span className="chain-badge" data-testid={testId} title="Designed for Robinhood Chain"><Leaf size={13}/><span>Robinhood Chain</span><span className="tiny-dot" /></span>;
export const AssetIcon = ({ symbol, small = false }) => <span className={`asset-icon asset-${symbol} ${small ? 'small' : ''}`} aria-hidden="true">{symbol === 'NVDA' ? <Cpu size={small ? 13 : 20}/> : symbol === 'GLD' ? <span className="gold-bars">▰</span> : symbol === 'AAPL' ? <svg viewBox="0 0 24 24" width="19" height="19" fill="currentColor"><path d="M17.1 12.5c0-2 1.7-3 1.8-3.1-1-1.4-2.4-1.5-3-1.5-1.3-.1-2.6.8-3.3.8-.7 0-1.8-.8-2.9-.8-1.5 0-2.9.9-3.7 2.2-1.6 2.7-.4 6.7 1.1 8.9.7 1 1.5 2.1 2.6 2.1 1-.1 1.4-.7 2.7-.7 1.2 0 1.6.7 2.7.6 1.1 0 1.8-1 2.5-2 .8-1.2 1.1-2.3 1.1-2.4-.1 0-2.1-.8-2.1-4.1zM15 6.5c.6-.8 1.1-1.9 1-3-.9.1-2 .6-2.7 1.4-.6.7-1.1 1.8-1 2.9 1 .1 2.1-.5 2.7-1.3z"/></svg> : symbol === 'TSLA' ? 'T' : 'G'} </span>;
export const SectionHeading = ({ eyebrow, title, description, action }) => <div className="page-heading"><div><div className="eyebrow" data-testid="page-eyebrow">{eyebrow}</div><h1 data-testid="page-title">{title}</h1>{description && <p data-testid="page-description">{description}</p>}</div>{action}</div>;
export const MetricStrip = () => {
  const { protocol } = useDemo();
  const stats = protocol.stats;
  return <section className="metric-strip" aria-label="Public protocol metrics" data-testid="public-protocol-metrics"><div className="metric"><span className="metric-label" data-testid="locked-label">INC LOCKED <Hexagon size={13}/></span><strong data-testid="locked-value">{number(stats.locked)} <small>INC</small></strong><span className="metric-foot" data-testid="locked-description">Across {stats.active} active protocol cycles</span></div><div className="metric"><span className="metric-label" data-testid="rewards-label">RWA REWARDS <ArrowUpRight size={14}/></span><strong data-testid="rewards-value">{money(stats.rewards)}</strong><span className="metric-foot" data-testid="rewards-description">Total protocol allocations</span></div><div className="metric"><span className="metric-label" data-testid="burned-label">TOTAL INC BURNED <Flame size={14} className="orange"/></span><strong data-testid="total-inc-burned-metric">{number(stats.burned)} <small>INC</small></strong><span className="metric-foot" data-testid="burned-description"><span className="orange">↗ 25%</span> of every completed cycle</span></div><div className="metric"><span className="metric-label" data-testid="cycle-label">INCUBATION CYCLE <span className="tiny-dot"/></span><strong data-testid="cycle-duration">02<span className="time-colon">:</span>00<span className="time-colon">:</span>00</strong><span className="metric-foot" data-testid="cycle-description"><span className="green">75% INC</span> returned at completion</span></div></section>;
};