import { ArrowDownLeft, ArrowUpRight, ChevronRight, Clock3, Flame, Hexagon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useDemo, number } from '../lib/demo';
import { AssetIcon } from './Common';

export const ProtocolRail = () => {
  const { state, catalog } = useDemo();
  return <aside className="protocol-rail"><section className="rail-section"><div className="rail-heading"><h2>The incubation loop</h2><span className="tiny-dot"/></div><div className="loop-steps"><div className="loop-step"><span className="step-icon"><Hexagon size={15}/></span><div><b>Commit INC</b><p>Fuel your incubation.</p></div><span className="step-number">01</span></div><div className="loop-step"><span className="step-icon"><Clock3 size={15}/></span><div><b>Let it incubate</b><p>One cycle. Two hours.</p></div><span className="step-number">02</span></div><div className="loop-step"><span className="step-icon green"><ArrowUpRight size={16}/></span><div><b>Reveal your RWA</b><p>Random asset. Random value.</p></div><span className="step-number">03</span></div></div><div className="token-split"><div><ArrowDownLeft size={14}/><strong>75%</strong><span>INC returned</span></div><div><Flame size={14}/><strong>25%</strong><span>INC burned</span></div></div><div className="split-line"><span/><i/></div><Link to="/protocol" className="subtle-link" data-testid="how-it-works-link">Explore the protocol <ArrowUpRight size={14}/></Link></section>
    <section className="rail-section"><div className="rail-heading"><h2>Inside the reward pool</h2><span className="count">05</span></div><div className="asset-stack">{catalog.assets.map(a => <Link to="/assets" key={a.symbol} className="asset-stack-row" data-testid={`pool-preview-${a.symbol}`}><AssetIcon symbol={a.symbol}/><div><b>{a.symbol}</b><small>{a.name}</small></div><span>{a.odds}%</span><ChevronRight size={12}/></Link>)}</div><div className="rail-note" data-testid="reward-odds-disclaimer">Illustrative assets & odds · Not live listings</div></section>
    <section className="rail-section activity-preview"><div className="rail-heading"><h2>Your latest activity</h2><ActivityDot/></div>{state.events.length ? state.events.slice(0, 3).map(e => <div className="mini-event" key={e.id} data-testid={`activity-preview-${e.id}`}><span className={`event-dot ${e.kind}`}/><div><b>{e.message}</b><small>{number(e.amount || 0)} {e.symbol}</small></div></div>) : <div className="quiet-state" data-testid="activity-empty">A fresh start.<br/><span>Your first cycle begins here.</span></div>}<Link className="subtle-link" to="/incubations" data-testid="all-activity-link">View all activity <ArrowUpRight size={14}/></Link></section>
  </aside>;
};
const ActivityDot = () => <span className="activity-dot"><i/><i/><i/></span>;