import { ArrowDownLeft, ArrowUpRight, ChevronRight, Clock3, Flame, Hexagon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useDemo, number } from '../lib/demo';
import { AssetIcon } from './Common';
import { activityMessage } from '../lib/activity';

export const ProtocolRail = () => {
  const { protocol, catalog } = useDemo();
  return <aside className="protocol-rail"><section className="rail-section"><div className="rail-heading"><h2>The incubation loop</h2><span className="tiny-dot"/></div><div className="loop-steps"><div className="loop-step"><span className="step-icon"><Hexagon size={15}/></span><div><b>Commit INC</b><p>Fuel the incubation.</p></div><span className="step-number">01</span></div><div className="loop-step"><span className="step-icon"><Clock3 size={15}/></span><div><b>Let it incubate</b><p>One cycle. Two hours.</p></div><span className="step-number">02</span></div><div className="loop-step"><span className="step-icon green"><ArrowUpRight size={16}/></span><div><b>Reveal the RWA</b><p>Random asset. Random value.</p></div><span className="step-number">03</span></div></div><div className="token-split"><div><ArrowDownLeft size={14}/><strong>75%</strong><span>INC returned</span></div><div><Flame size={14}/><strong>25%</strong><span>INC burned</span></div></div><div className="split-line"><span/><i/></div><Link to="/docs" className="subtle-link" data-testid="how-it-works-link">Explore the protocol <ArrowUpRight size={14}/></Link></section>
    <section className="rail-section"><div className="rail-heading"><h2>Inside the reward pool</h2><span className="count">05</span></div><div className="asset-stack">{catalog.assets.map(a => <Link to="/assets" key={a.symbol} className="asset-stack-row" data-testid={`pool-preview-${a.symbol}`}><AssetIcon symbol={a.symbol}/><div><b>{a.symbol}</b><small>{a.name}</small></div><span>{a.odds}%</span><ChevronRight size={12}/></Link>)}</div><Link to="/docs#docs-rarity" className="rail-note subtle-link" data-testid="reward-pool-note">4 rarity tiers · $1–$500<ArrowUpRight size={12}/></Link></section>
    <section className="rail-section activity-preview"><div className="rail-heading"><h2>Protocol activity</h2><span className="tiny-dot"/></div>{protocol.events.length ? protocol.events.slice(0, 3).map(e => <div className="mini-event" key={e.id} data-testid={`activity-preview-${e.id}`}><span className={`event-dot ${e.kind}`}/><div><b>{activityMessage(e)}</b><small>{number(e.amount || 0)} {e.symbol}</small></div></div>) : <div className="quiet-state" data-testid="activity-empty">The next cycle starts here.<br/><span>Public allocations appear as cycles begin.</span></div>}<Link className="subtle-link" to="/activity" data-testid="all-activity-link">View protocol activity <ArrowUpRight size={14}/></Link></section>
  </aside>;
};