import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, BookOpen, ChevronDown, Clock3, Fingerprint, Flame, Globe2, Hexagon, Layers3, Sparkles, Wallet } from 'lucide-react';
import { useDemo } from '../lib/demo';
import { AssetIcon } from '../components/Common';
import { PodScene } from '../components/PodScene';
import { RarityTiers } from '../components/RarityTiers';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../components/ui/accordion';

const sections = [['overview', 'The protocol'], ['cycle', 'The incubation cycle'], ['rarity', 'Rarity & drop rates'], ['assets', 'The asset universe'], ['tokenomics', 'The INC economy'], ['connection', 'Wallet connection'], ['questions', 'Common questions']];
const faqs = [
  ['What determines a reward?', 'Each completed cycle independently selects a rarity tier and an RWA asset. A USD amount is then drawn within the selected tier’s range. Every cent value within that range is equally likely.'],
  ['Can any RWA asset receive a Legendary reward?', 'Yes. All five assets are eligible for all four tiers. Asset probability and rarity probability are independent: a Legendary NVDA result has a 4% × 25% = 1% probability per cycle.'],
  ['Does committing more INC increase the odds?', 'No. The committed amount changes the INC returned and burned. Core, Prism, and Onyx pod models share the same rarity odds, asset odds, and value ranges.'],
  ['When are the 75% return and 25% burn applied?', 'Both happen automatically at the end of the two-hour cycle. Claiming the RWA reward is a separate action and does not return INC twice. Closing the browser does not cancel the timer.'],
  ['Are allocations shared between wallets?', 'Protocol statistics and activity are public and combine wallet participation. INC balances, incubation actions, and reward claims are scoped to the connected, signature-verified wallet. Reconnecting the same wallet restores its allocations.'],
  ['How do reward cards work?', 'After a reward is claimed, Create reward card publishes a shareable allocation record. The card can be downloaded as a PNG or shared with a public link. It includes the asset, value, rarity, cycle and shortened wallet address—not the wallet’s balance.'],
  ['Does the INC burn guarantee growth?', 'No. Removing INC from circulation reduces the recorded supply, but does not guarantee price appreciation, liquidity, or ecosystem growth. Reward values are estimates, not fixed investment returns.'],
];
const DocTitle = ({ number, id, title, subtitle }) => <div className="doc-section-heading"><span>{number} / FIELD NOTES</span><h2 id={id}>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>;

export default function Docs() {
  const { catalog } = useDemo();
  const [active, setActive] = useState('overview');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id.replace('docs-', '')); }), { rootMargin: '-10% 0px -65% 0px' });
    document.querySelectorAll('.doc-section').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  return <div className="docs-page">
    <section className="docs-hero"><div className="docs-hero-copy"><div className="hero-eyebrow" data-testid="docs-eyebrow"><span className="eyebrow-line"/>INC.HOOD / PROTOCOL DOCUMENTATION</div><h1 data-testid="docs-title">THE PROTOCOL,<br/><span>DECODED.</span></h1><p data-testid="docs-introduction">A shared incubation layer for real-world possibilities.<br/>The mechanics behind every cycle, allocation, and burn.</p><div className="docs-hero-meta"><span><BookOpen size={12}/>FIELD GUIDE 01</span><span>7 MIN READ</span><span>V.02</span></div></div><div className="docs-pod-object"><PodScene hero testId="docs-hero-pod"/><span>INC.HOOD / THE CORE MECHANISM</span></div><div className="docs-hero-index">01—07<br/><span>OPEN KNOWLEDGE</span></div></section>
    <div className="docs-facts" data-testid="docs-facts"><div><Clock3 size={15}/><b>02 hours</b><span>One full cycle</span></div><div><Layers3 size={15}/><b>05 assets</b><span>One shared pool</span></div><div><Sparkles size={15}/><b>04 tiers</b><span>A spectrum of rarity</span></div><div><Flame size={15}/><b>75 / 25</b><span>Return meets burn</span></div></div>
    <div className="docs-layout"><aside className="docs-index"><div className="docs-index-title"><span>IN THIS FIELD GUIDE</span><span>↓</span></div><nav aria-label="Documentation sections">{sections.map(([id, title], i) => <a key={id} href={`#docs-${id}`} className={active === id ? 'active' : ''} onClick={() => setActive(id)} data-testid={`docs-nav-${id}`}><span>0{i + 1}</span>{title}<ArrowUpRight size={12}/></a>)}</nav><Link to="/zone" className="docs-back-link" data-testid="docs-enter-zone">Enter the Zone<ArrowUpRight size={15}/></Link><div className="docs-index-note"><Hexagon size={20}/><p>One protocol.<br/>A shared horizon.</p></div></aside>
      <div className="docs-content">
        <section className="doc-section" id="docs-overview" data-testid="docs-section-overview"><DocTitle number="01" title="Potential, put into motion." subtitle="What is Inc.hood?"/><p className="doc-lead">Inc.hood is an RWA incubation experience designed for Robinhood Chain. INC fuels time-bound pods, each concluding with a random real-world asset reward.</p><div className="doc-two-col"><p>The Zone is the public face of the protocol: shared statistics, shared activity, and a common reward universe. Participation starts with a connected EVM wallet—not an email or individual profile.</p><p>Each allocation remains linked to the verified wallet. At cycle completion, 75% of committed INC returns, 25% is burned, and one RWA reward becomes available to claim.</p></div><div className="doc-principles"><span><Globe2 size={16}/>Public by perspective</span><span><Wallet size={16}/>Wallet-bound allocations</span><span><Hexagon size={16}/>INC-powered cycles</span></div></section>
        <section className="doc-section" id="docs-cycle" data-testid="docs-section-cycle"><DocTitle number="02" title="From commitment to allocation." subtitle="One cycle. Three stages. Two hours."/><div className="docs-cycle-flow">{[[Hexagon, '01', 'Commit INC', 'A connected wallet selects a pod and an INC amount. The full commitment leaves the available balance.'], [Clock3, '02', 'Incubate', 'The 7,200-second cycle begins. Its timer persists even when the browser closes.'], [Sparkles, '03', 'Reveal & claim', 'The engine selects the tier, asset, and nominal value. INC settles automatically; the RWA is ready to claim.']].map(([Icon, n, title, text]) => <div key={n}><span className="docs-step-label">{n}<Icon size={20}/></span><h3>{title}</h3><p>{text}</p></div>)}</div><div className="doc-equation"><span>INC COMMITMENT</span><ArrowRight size={15}/><span>02:00:00</span><ArrowRight size={15}/><b>RWA ALLOCATION + 75% INC RETURN</b></div></section>
        <section className="doc-section" id="docs-rarity" data-testid="docs-section-rarity"><DocTitle number="03" title="Not every reveal is equal." subtitle="The rarity matrix"/><p>A tier determines the reward’s estimated USD range. Its drop rate is the probability of that tier on any single cycle—not a quota or a promise after a fixed number of attempts.</p><RarityTiers prefix="docs-tier"/><div className="docs-odds-total"><span><span className="tiny-dot"/>INDEPENDENT DRAWS</span><b>60 + 25 + 11 + 4 = 100%</b></div><div className="doc-two-col"><p><b>Every tier, every asset.</b> Common, Rare, Epic, and Legendary can each produce any asset in the pool. Rarity is independent of the asset ticker.</p><p><b>Same rules across pod series.</b> The Core, Prism, and Onyx designs do not change the chances. Larger INC commitments do not increase the reward range.</p></div></section>
        <section className="doc-section" id="docs-assets" data-testid="docs-section-assets"><DocTitle number="04" title="Familiar assets. New outcomes." subtitle="The RWA universe"/><p>The reward universe spans technology, consumer markets, automotive innovation, and gold exposure. Ticker selection follows its own distribution.</p><div className="docs-assets-list">{catalog.assets.map(a => <div key={a.symbol} data-testid={`docs-asset-${a.symbol}`}><AssetIcon symbol={a.symbol}/><b>{a.symbol}</b><span>{a.name}</span><small>{a.category}</small><strong>{a.odds}%</strong></div>)}</div><Link to="/assets" className="docs-text-link" data-testid="docs-view-assets">Explore the reward pool<ArrowUpRight size={14}/></Link></section>
        <section className="doc-section" id="docs-tokenomics" data-testid="docs-section-tokenomics"><DocTitle number="05" title="Circulate less. Keep the cycle moving." subtitle="The 75 / 25 principle"/><div className="docs-split"><div><ArrowDownLeft size={20}/><strong>75<span>%</span></strong><b>RETURNED TO THE WALLET</b><p>Automatically restored to the available INC balance at completion.</p></div><div><Flame size={20}/><strong>25<span>%</span></strong><b>REMOVED FROM CIRCULATION</b><p>The burn is permanent within the allocation ledger, independent of the reward claim.</p></div></div><div className="economy-bar"><div/><span/></div><div className="doc-equation"><span>100 INC COMMITTED</span><ArrowRight size={15}/><b>75 INC RETURNED</b><span>+</span><em>25 INC BURNED</em></div><p className="doc-small">The RWA reward is separate from the INC return. A 75% return is not a 75% yield, and the burn does not guarantee token appreciation.</p></section>
        <section className="doc-section" id="docs-connection" data-testid="docs-section-connection"><DocTitle number="06" title="A wallet is the key." subtitle="Connect before allocation"/><div className="doc-two-col"><p>MetaMask and compatible injected EVM wallets connect directly through the browser. A standard message signature verifies ownership before incubation purchases or claims are enabled.</p><p>The connected address identifies the allocation ledger. Switching addresses clears the previous wallet’s view; reconnecting an address restores its existing INC balance and rewards.</p></div><div className="doc-connection-note"><Fingerprint size={22}/><div><b>Approval, signature, connection.</b><span>The connection flow never requests a private key or sends a blockchain transaction.</span></div></div></section>
        <section className="doc-section" id="docs-questions" data-testid="docs-section-questions"><DocTitle number="07" title="The details that matter." subtitle="Common questions"/><Accordion type="single" collapsible className="faq-list">{faqs.map(([question, answer], i) => <AccordionItem value={String(i)} key={question}><AccordionTrigger data-testid={`faq-${i}`}>{question}</AccordionTrigger><AccordionContent data-testid={`faq-answer-${i}`}>{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
        <div className="docs-end"><div><span>THE NEXT CHAPTER STARTS IN THE ZONE</span><h2>Less mystery. More possibility.</h2></div><Link to="/zone" className="primary-link" data-testid="docs-bottom-zone">Explore the Zone<ArrowUpRight size={16}/></Link></div>
      </div>
    </div>
  </div>;
}