import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, ArrowDownLeft, Box, Clock3, Flame, Hexagon, Sparkles } from 'lucide-react';
import { AssetIcon, SectionHeading } from '../components/Common';
import { Button } from '../components/ui/button';
import { PodCard } from '../components/PodCard';
import { money, number, useDemo } from '../lib/demo';
import { activityMessage } from '../lib/activity';

export default function Incubations({ onReveal }) {
  const { state, catalog, busy } = useDemo();
  const [tab, setTab] = useState('active');
  const claimed = state.runs.filter(r => r.status === 'claimed');
  const active = state.runs.filter(r => r.status !== 'claimed');
  const total = claimed.reduce((sum, r) => sum + r.reward.amount, 0);
  const holdings = catalog.assets.map(a => ({ ...a, value: claimed.filter(r => r.reward.symbol === a.symbol).reduce((sum, r) => sum + r.reward.amount, 0), quantity: claimed.filter(r => r.reward.symbol === a.symbol).reduce((sum, r) => sum + r.reward.quantity, 0) })).filter(a => a.value > 0);
  return <div className="secondary-page"><SectionHeading eyebrow="YOUR PERSONAL INCUBATION TERMINAL" title={<>Your cycles.<br/><span className="green">Your possibilities.</span></>} description="Track your incubations, claimed assets, and every INC along the way." action={<Link className="primary-link" to="/zone" data-testid="new-incubation-link">New incubation <ArrowUpRight size={16}/></Link>}/>
    <div className="portfolio-metrics"><div><span>CLAIMED RWA VALUE</span><strong data-testid="portfolio-total">{money(total)}</strong><small data-testid="portfolio-value-caption">Your collected RWA rewards</small></div><div><span>AVAILABLE BALANCE</span><strong data-testid="portfolio-inc-balance">{number(state.balance)} <small>INC</small></strong><small>Ready for your next cycle</small></div><div><span>INC RETURNED</span><strong className="green" data-testid="portfolio-returned">{number(state.total_returned)} <small>INC</small></strong><small>75% of completed cycles</small></div><div><span>INC BURNED</span><strong className="orange" data-testid="portfolio-burned">{number(state.total_burned)} <small>INC</small></strong><small data-testid="portfolio-burn-caption">Permanently removed from supply</small></div></div>
    <div className="portfolio-tabs">{[['active', 'Active incubations', active.length], ['holdings', 'My assets', holdings.length], ['history', 'Activity', state.events.length]].map(([id, name, count]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)} data-testid={`portfolio-tab-${id}`}>{name}<span>{count}</span></button>)}</div>
    {tab === 'active' && (active.length ? <div className="portfolio-pods">{active.map(r => <PodCard key={r.id} pod={catalog.pods.find(p => p.id === r.pod_id)} run={r} cost={r.amount} onReveal={onReveal} busy={busy}/>)}</div> : <Empty icon={Box} title="Your next asset starts with a cycle." text="No active incubations. The Zone is ready when you are."/>)}
    {tab === 'holdings' && (holdings.length ? <div className="holdings-table"><div className="table-header"><span>ASSET</span><span>QUANTITY</span><span>CLAIMED VALUE</span><span>ALLOCATION</span></div>{holdings.map(a => <div className="holding-row" key={a.symbol} data-testid={`holding-${a.symbol}`}><div><AssetIcon symbol={a.symbol}/><span><b>{a.symbol}</b><small>{a.name}</small></span></div><span data-testid={`holding-quantity-${a.symbol}`}>{a.quantity.toFixed(6)}</span><strong data-testid={`holding-value-${a.symbol}`}>{money(a.value)}</strong><div className="allocation"><span>{(a.value / total * 100).toFixed(1)}%</span><i style={{ width: `${a.value / total * 100}%`, background: a.color }}/></div></div>)}<div className="table-note" data-testid="holdings-note">Fractional quantities use the reference price at reward generation.</div></div> : <Empty icon={Sparkles} title="A portfolio of possibilities." text="Claim your first RWA reward to start your collection."/>)}
    {tab === 'history' && (state.events.length ? <div className="activity-table">{state.events.map(e => <div className="activity-row" key={e.id} data-testid={`activity-row-${e.id}`}><span className={`activity-icon ${e.kind}`}>{e.kind === 'burn' ? <Flame size={17}/> : e.kind === 'return' || e.kind === 'deposit' ? <ArrowDownLeft size={17}/> : e.kind === 'claim' ? <Sparkles size={17}/> : <Hexagon size={17}/>}</span><div><b>{activityMessage(e)}</b><small>{new Date(e.timestamp * 1000).toLocaleString()}</small></div><span className={e.kind === 'burn' ? 'orange' : ''}>{e.kind === 'claim' || e.kind === 'ready' ? money(e.amount) : `${number(e.amount)} INC`}</span></div>)}</div> : <Empty icon={Clock3} title="A clean slate." text="Every cycle, return, burn, and reward will appear here."/>)}
  </div>;
}
const Empty = ({ icon: Icon, title, text }) => <div className="empty-state portfolio-empty" data-testid="portfolio-empty"><Icon size={35}/><h2>{title}</h2><p>{text}</p><Link to="/zone" data-testid="portfolio-empty-zone-link"><Button>Explore the Zone<ArrowRight size={15}/></Button></Link></div>;