import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, ArrowDownLeft, Box, Clock3, Flame, Hexagon, Share2, Sparkles, Wallet } from 'lucide-react';
import { AssetIcon, SectionHeading } from '../components/Common';
import { TierBadge } from '../components/RarityTiers';
import { Button } from '../components/ui/button';
import { PodCard } from '../components/PodCard';
import { money, number, useDemo } from '../lib/demo';
import { shortAddress } from '../lib/wallet';
import { activityMessage } from '../lib/activity';

export default function Incubations({ onReveal, onShare, onConnect }) {
  const { state, catalog, wallet, busy } = useDemo();
  const [tab, setTab] = useState('active');
  const claimed = state.runs.filter(r => r.status === 'claimed');
  const active = state.runs.filter(r => r.status !== 'claimed');
  const total = claimed.reduce((sum, r) => sum + r.reward.amount, 0);
  const holdings = catalog.assets.map(a => ({ ...a, value: claimed.filter(r => r.reward.symbol === a.symbol).reduce((sum, r) => sum + r.reward.amount, 0), quantity: claimed.filter(r => r.reward.symbol === a.symbol).reduce((sum, r) => sum + r.reward.quantity, 0) })).filter(a => a.value > 0);
  return <div className="secondary-page"><SectionHeading eyebrow={wallet ? `WALLET ALLOCATIONS / ${shortAddress(wallet.address)}` : 'INC.HOOD / WALLET ALLOCATIONS'} title={<>Connected capital.<br/><span className="green">Recorded possibilities.</span></>} description="Incubation commitments, claimed RWA assets, and cycle records linked to a verified wallet." action={<Link className="primary-link" to="/zone" data-testid="new-incubation-link">New incubation <ArrowUpRight size={16}/></Link>}/>
    {!wallet ? <div className="wallet-gate" data-testid="wallet-holdings-gate"><Wallet size={38}/><h2>A wallet connects the records.</h2><p>Connect an EVM wallet to view balances, allocations, and claimed rewards.</p><Button onClick={onConnect} data-testid="holdings-connect-button"><Wallet size={15}/>Connect wallet</Button></div> : <>
    <div className="portfolio-metrics"><div><span>CLAIMED RWA VALUE</span><strong data-testid="portfolio-total">{money(total)}</strong><small>Collected RWA allocations</small></div><div><span>AVAILABLE BALANCE</span><strong data-testid="portfolio-inc-balance">{number(state.balance)} <small>INC</small></strong><small>Available for incubation</small></div><div><span>INC RETURNED</span><strong className="green" data-testid="portfolio-returned">{number(state.total_returned)} <small>INC</small></strong><small>75% of completed cycles</small></div><div><span>INC BURNED</span><strong className="orange" data-testid="portfolio-burned">{number(state.total_burned)} <small>INC</small></strong><small>Permanently removed from supply</small></div></div>
    <div className="portfolio-tabs">{[['active', 'Active cycles', active.length], ['holdings', 'RWA assets', holdings.length], ['cards', 'Reward cards', claimed.length], ['history', 'Activity', state.events.length]].map(([id, name, count]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)} data-testid={`portfolio-tab-${id}`}>{name}<span>{count}</span></button>)}</div>
    {tab === 'active' && (active.length ? <div className="portfolio-pods">{active.map(r => <PodCard key={r.id} pod={catalog.pods.find(p => p.id === r.pod_id)} run={r} cost={r.amount} onReveal={onReveal} busy={busy}/>)}</div> : <Empty icon={Box} title="The next asset starts with a cycle." text="No active allocations for the connected wallet."/>)}
    {tab === 'holdings' && (holdings.length ? <div className="holdings-table"><div className="table-header"><span>ASSET</span><span>QUANTITY</span><span>CLAIMED VALUE</span><span>ALLOCATION</span></div>{holdings.map(a => <div className="holding-row" key={a.symbol} data-testid={`holding-${a.symbol}`}><div><AssetIcon symbol={a.symbol}/><span><b>{a.symbol}</b><small>{a.name}</small></span></div><span data-testid={`holding-quantity-${a.symbol}`}>{a.quantity.toFixed(6)}</span><strong data-testid={`holding-value-${a.symbol}`}>{money(a.value)}</strong><div className="allocation"><span>{(a.value / total * 100).toFixed(1)}%</span><i style={{ width: `${a.value / total * 100}%`, background: a.color }}/></div></div>)}<div className="table-note">Fractional quantities use the reference price at allocation.</div></div> : <Empty icon={Sparkles} title="A portfolio of possibilities." text="Claimed RWA rewards appear in wallet holdings."/>)}
    {tab === 'cards' && (claimed.length ? <div className="claimed-card-grid">{claimed.map(run => <article className="claimed-card" key={run.id} data-testid={`claimed-card-${run.id}`}><div><TierBadge tier={run.reward.tier} testId={`card-tier-${run.id}`}/><span>{run.id.slice(0, 8).toUpperCase()}</span></div><AssetIcon symbol={run.reward.symbol}/><h2>{run.reward.symbol}<strong>{money(run.reward.amount)}</strong></h2><p>{new Date(run.claimed_at * 1000).toLocaleDateString()} · {number(run.amount)} INC cycle</p><Button variant="outline" disabled={busy} onClick={() => onShare(run)} data-testid={`share-claimed-${run.id}`}><Share2 size={14}/>Create reward card</Button></article>)}</div> : <Empty icon={Share2} title="Every reveal can become a collectible." text="Claim a reward to create its downloadable allocation card."/>)}
    {tab === 'history' && (state.events.length ? <div className="activity-table">{state.events.map(e => <div className="activity-row" key={e.id} data-testid={`activity-row-${e.id}`}><span className={`activity-icon ${e.kind}`}>{e.kind === 'burn' ? <Flame size={17}/> : e.kind === 'return' || e.kind === 'deposit' ? <ArrowDownLeft size={17}/> : e.kind === 'claim' ? <Sparkles size={17}/> : <Hexagon size={17}/>}</span><div><b>{activityMessage(e)}</b><small>{new Date(e.timestamp * 1000).toLocaleString()}</small></div><span className={e.kind === 'burn' ? 'orange' : ''}>{e.kind === 'claim' || e.kind === 'ready' ? money(e.amount) : `${number(e.amount)} INC`}</span></div>)}</div> : <Empty icon={Clock3} title="A clean slate." text="Cycles, returns, burns, and claims appear as allocations progress."/>)}
    </>}
  </div>;
}
const Empty = ({ icon: Icon, title, text }) => <div className="empty-state portfolio-empty" data-testid="portfolio-empty"><Icon size={35}/><h2>{title}</h2><p>{text}</p><Link className="primary-link" to="/zone" data-testid="portfolio-empty-zone-link">Explore the Zone<ArrowRight size={15}/></Link></div>;